# Generated by Django 2.0.5 on 2018-09-27 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 8, 10, 6, 593411, tzinfo=utc), help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='description',
            field=models.CharField(help_text='描述', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='icon_url',
            field=models.ImageField(blank=True, help_text='图标', null=True, upload_to='gategory/icons', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='image_url',
            field=models.ImageField(help_text='图片', upload_to='gategory/images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='is_in_serving',
            field=models.BooleanField(default=True, help_text='是否在服务区内', verbose_name='是否在服务区内'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='link',
            field=models.URLField(blank=True, help_text='链接', null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='title',
            field=models.CharField(help_text='标题', max_length=60, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='title_color',
            field=models.CharField(blank=True, help_text='颜色', max_length=30, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='gategory',
            name='v',
            field=models.SmallIntegerField(default=0, help_text='数据的版本号', verbose_name='数据的版本号'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(help_text='地址', max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(help_text='城市', max_length=60, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geohash',
            field=models.CharField(help_text='经度,纬度', max_length=120, verbose_name='经度,纬度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(help_text='经度', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(help_text='纬度', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='显示地址', max_length=200, verbose_name='显示地址'),
        ),
    ]
