# Generated by Django 2.0.5 on 2018-09-27 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180927_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gategory',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间', verbose_name='添加时间'),
        ),
    ]
