# Generated by Django 2.0.5 on 2018-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_supports__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='shop',
            name='distance',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='距离'),
        ),
        migrations.AddField(
            model_name='shop',
            name='order_lead_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='预计送达时间'),
        ),
    ]
