# Generated by Django 2.0.5 on 2018-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20180927_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='supports',
        ),
        migrations.AddField(
            model_name='shop',
            name='supports',
            field=models.ManyToManyField(blank=True, null=True, to='business.Supports', verbose_name='保障'),
        ),
    ]
