# Generated by Django 2.0.5 on 2018-10-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20180929_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='supports',
            field=models.ManyToManyField(blank=True, null=True, related_name='_shop_supports_+', to='business.Supports', verbose_name='保障'),
        ),
        migrations.AlterField(
            model_name='supports',
            name='_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='保障的id == key'),
        ),
    ]
