# Generated by Django 2.0.5 on 2018-09-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vertifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertifycode',
            name='img_content',
            field=models.ImageField(upload_to='captcha/', verbose_name='传入前台的图片配置'),
        ),
    ]
